source 'http://rubygems.org'

gem 'rhosync', '~> 2.2.0' 
# By default to run application Mongrel web server is used
gem 'mongrel', '~> 1.1.5'
# If you prefer you can use Thin web server instead of Mongrel
# gem 'thin', '1.2.11'

group :test do
  gem 'rack-test', '>= 0.5.3', :require => "rack/test"
  gem 'rspec', '~> 2.5.0'
  gem 'rcov', '>= 0.9.8'
end
