# Try to load vendor-ed rhosync tasks, otherwise load the gem
begin
  require 'vendor/rhosync/lib/rhosync/tasks'
rescue LoadError
  require 'rhosync/tasks'
end

begin
  require 'resque/tasks'

  task "resque:setup" do
    require 'rhosync'
    require '<%=name%>'
  end
rescue LoadError
  puts "Resque not available. Install it with: "
  puts "gem install resque\n\n"
end