$:.unshift File.join(File.dirname(__FILE__),'..','..','lib')
require 'rhosync/tasks'

ROOT_PATH = File.expand_path(File.dirname(__FILE__))

begin
  require 'resque/tasks'
  task "resque:setup" do
    require 'application'
  end
rescue LoadError
  puts "Resque not available. Install it with: "
  puts "gem install resque\n\n"
end